[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
lint.select = ["E", "F", "I"]
lint.fixAll = true
format.preview = true
codeAction.fixAll.enable = true
codeAction.organizeImports.enable = true

[language-server.jedi-language-server]
command = "jedi-language-server"

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-ci", "-sr"] }

[[language]]
name = "markdown"
auto-format = true
language-servers = []
formatter = { command = "mdformat", args = ["-"] }

[[language]]
name = "python"
auto-format = true
language-servers = ["ruff", "jedi-language-server"]

[language.formatter]
command = "sh"
args = [
  "-c",
  "tmp=$(mktemp --suffix=.py) && cat > $tmp && ruff check --select I --fix --unsafe-fixes $tmp >/dev/null 2>&1 ; ruff format --quiet $tmp >/dev/null 2>&1 && cat $tmp && rm $tmp"
]

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python3"
args = ["-m", "debugpy.adapter"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [{ name = "entrypoint", completion = "filename", default = "." }]

[language.debugger.templates.args]
mode = "debug"
program = "{0}"

[[language]]
name = "json"
auto-format = true
formatter = { command = "jq", args = ["."] }
