[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
lint.select = ["E", "F", "I"]
lint.fixAll = true
format.preview = true
codeAction.fixAll.enable = true
codeAction.organizeImports.enable = true

[language-server.jedi-language-server]
command = "jedi-language-server"
config.workspace.environmentPath = ".venv/bin/python"

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-i", "2", "-ci", "-sr"] }

[[language]]
name = "markdown"
auto-format = true
language-servers = []
formatter = { command = "mdformat", args = ["-"] }

[[language]]
name = "python"
auto-format = true
language-servers = ["ruff", "jedi-language-server"]

[language.formatter]
command = "sh"
args = [
  "-c",
  "tmp=$(mktemp --suffix=.py) && cat > $tmp && ruff check --select I --fix --unsafe-fixes $tmp >/dev/null 2>&1 ; ruff format --quiet $tmp >/dev/null 2>&1 && cat $tmp && rm $tmp"
]

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python3"
args = ["-m", "debugpy.adapter"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [{ name = "entrypoint", completion = "filename", default = "." }]

[language.debugger.templates.args]
mode = "debug"
program = "{0}"

[[language]]
name = "json"
auto-format = true
formatter = { command = "jq", args = ["."] }

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.typescript-language-server.config.typescript.inlayHints]
includeInlayParameterNameHints = "all"
includeInlayFunctionParameterTypeHints = true
includeInlayVariableTypeHints = true
includeInlayPropertyDeclarationTypeHints = true
includeInlayFunctionLikeReturnTypeHints = true

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
auto-format = true

[language-server.gopls]
command = "gopls"
[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[[language]]
name = "go"
auto-format = true
language-servers = ["gopls"]
formatter = { command = "gofumpt" }

[language.debugger]
name = "go"
transport = "stdio"
command = "dlv"
args = ["dap"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [{ name = "entrypoint", completion = "filename", default = "." }]
[language.debugger.templates.args]
mode = "debug"
program = "{0}"

[[language.debugger.templates]]
name = "binary"
request = "launch"
[language.debugger.templates.args]
mode = "exec"
program = "{0}"

[[language]]
name = "gomod"
auto-format = true
language-servers = ["gopls"]

[[language]]
name = "gowork"
auto-format = true
language-servers = ["gopls"]

[[language]]
name = "gotmpl"
auto-format = true
language-servers = ["gopls"]


[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "babel"] }
